spring:
  profiles:
    active: ${SPRING_PROFILE:dev}
  application:
    name: retail_manager
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: false
    cloud-platform: none
    allow-circular-references: false
    lazy-initialization: false
    log-startup-info: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:h2:file:./H2DB.db;
    username: retail_manager
    password: retail_manager
    driver-class-name: org.h2.Driver
    hikari:
      allow-pool-suspension: false
      maximum-pool-size: 5
  flyway:
    enabled: false
    locations:
      - classpath:db/migrations/{vendor}
    connect-retries: 3
    connect-retries-interval: 5s
    driver-class-name: jdbc:h2:file:./H2DB.db
    clean-disabled: true
    execute-in-transaction: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    bootstrap: default
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  data:
    redis:
      client-type: lettuce
      host: localhost
      port: 5000
      username: retail_cache
      password: retail_cache
      timeout: 3000ms
      database: 0
      repositories:
        enabled: false
      lettuce:
        pool:
          enabled: false
          max-active: 4
          max-idle: 4
          max-wait: 1ms
          min-idle: 0
          time-between-eviction-runs: 5ms
management:
  health:
    redis:
      enabled: false