spring:
  profiles:
    active: ${SPRING_PROFILE:dev}
  application:
    name: retail_manager
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: false
    cloud-platform: none
    allow-circular-references: false
    lazy-initialization: false
    log-startup-info: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  docker:
    compose:
      enabled: false
  datasource:
    url: "jdbc:h2:file:./target/db/H2DB.db;DATABASE_TO_UPPER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;"
    username: dev
    password: dev
    hikari:
      allow-pool-suspension: false
      maximum-pool-size: 5
  flyway:
    enabled: true
    table: production_flyway_migrations
    output-query-results: true
    out-of-order: false
    locations:
      - classpath:db/migration
    execute-in-transaction: true
    validate-on-migrate: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl
    database-platform: org.hibernate.dialect.H2Dialect